### ISSUE TITLE
Drop `easy_localization` compatibility mode

### ISSUE THREAD

**Issue by Albert221** [leancodepl/poe2arb#40]
The `--el-compat` flag along with its functionalities was introduced for a smooth transition from the LeanCode's bash scripts integration with `easy_localization` to the poe2arb with `flutter_localizations`. No new projects use `easy_localization` at LeanCode anymore.

Should we drop it with the next major release?

**Comment by bartekpacia** [comment]
By "next major release" you mean v0.4.0, right?

**Comment by Albert221** [comment]
Yes
