### ISSUE TITLE
Constraining poe2arb version for a project

### ISSUE THREAD

**Issue by Albert221** [leancodepl/poe2arb#52]
To prevent different people from one project from using different poe2arb versions (which may result in different ARB outputs, bloated diffs, etc.) we may introduce something like a `poe2arb-version` constraint in `l10n.yaml`, which would specify a required `poe2arb` version to be run with.

It could specify:
* a specific version `0.5.1`
* version range `>= 0.5.-`, `>=0.5.0 <0.7`
* minor version `^0.5.0`

That's rather low priority

**Comment by shilangyu** [comment]
Or poe2arb binary could be distributed through a pub package, and leave version management to pub. "Constraining poe2arb version for a project" is not enough, we would then need to solve the problem of having many poe2arb version on one system. Pub would solve both problems, usage would then be through `pub run`.
