### ISSUE TITLE
Proposal: Make String a default placeholder type

### ISSUE THREAD

**Issue by Albert221** [leancodepl/poe2arb#70]
### Proposal
Currently Flutter fallbacks placeholders with no `type` specified to `Object`, which are `toString()`ed. This proposal is to always have the type of placeholders set in poe2arb, falling back to `String` if no type is specified for all cases except `count` placeholder in plural term.

### Changes
| Plural | Placeholder | Before | After |
|:-:|-|-|-|
| | `{name}` | `Object name` | `String name` ❗ |
| | `{name,String}` | `String name` | `String name` |
| | `{name,Object}` | `Object name` | `Object name` |
| ☑️ | `{count}` | `num count` | `num count` |

This would increment the tool's major version.

### Compatibility
There is a possibility for adding a flag (cmdline and/or `l10n.yaml`) for falling back to the previous behavior (`Object` as default). I don't think this is needed, as the migration would be straightforward.

On the other hand, this change would be problematic for people that work on two or more projects, where at least one of them didn't migrate.

### Migration
All affected places in Dart code would now expect `String` type instead of `Object`. Simply `toString()` the old argument to preserve the behavior.

**Comment by shilangyu** [comment]
Since this will bump the major version I think its perfectly acceptable to not provide a compatibility layer. I would argue the surface area of this change isnt that big (and very easy to fix). Im all for this change.

**Comment by bartekpacia** [comment]
Sounds like a nice default to me.

RE compatibility: if major is bumped, then why care? I agree with @shilangyu.

**Comment by Albert221** [comment]
It will be implemented in 2.0.0
