### ISSUE TITLE
Term prefix filters

### ISSUE THREAD

**Issue by Albert221** [leancodepl/poe2arb#76]
There are some projects that are made of more than one Dart package containing ARB files. Such example can be an app which has different feature sets in separate Dart packages with separate localization files or an app that has a design system as a separate package.

For many different reasons, it's preferred to still keep all terms and translations withing one POEditor project.

Therefore I propose to introduce something called ***prefix filter***.

* Terms (their names) in POEditor could be prefixed with `some_string:`
* In `l10n.yaml` file you could optionally define a `term-prefix: some_string`
  * You could define only one particular filter, as accepting more than one could make ARB to POEditor import nondeterministic.
* This would make `poe2arb poe` import only the strings prefixed with the given string, stripped of it in the ARBs. If no prefix filter is specified, it defaults to no prefix.

| Term name in POE | `term-prefix` | Term name in ARB |
|-|-|-|
| `fooBar` | none or `''` | `fooBar` |
| `fooBar` | `blueberry` | not imported |
| `blueberry:fooBar` | none or `''` | not imported |
| `blueberry:fooBar` | `blueberry` | `fooBar` |

**Comment by shilangyu** [comment]
I am not convinced about forcing `:` to be the separator of the prefix and term. Maybe the `term-prefix` should just accept the prefix together with a separator if a user wants one?

**Comment by Albert221** [comment]
What disadvantages do you see with the `:`?

I think using a name that's otherwise illegal to be used for the term name (as the colon) will prevent situations, where a term was named using the prefix accidentally (e.g. my `term-prefix` is `something` and I created a term starting with `something` because that was its context, I didn't want this term to be _prefixed_.

Also, with a character like that it's easy to distinguish what is prefixed (and then decide whether the prefix matches our filter) and what is not. With a free-text prefix we can't know of available prefixes and hence when using empty `term-prefix` we'll include prefixed terms.

**Comment by Albert221** [comment]
> What if someone wants to include terms from multiple "namespaces"?

That would be incorrect by design. The term prefix is designed to be used to filter terms to different packages. Also, accepting multiple term prefixes introduces a problem of conflicting names for terms under different prefixes, and makes #75 impossible to implement, as we won't be able to know what prefix to export to.
