### ISSUE TITLE
Rename download arb filename

### ISSUE THREAD

**Issue by RoyZengTW** [leancodepl/poe2arb#80]
I use poe2arb poe command to download arb file.
The filename is app_en-hk.arb but the flutter needs the name app_en_hk.arb.
Does poe2arb have options to rename file?

Thanks.

**Comment by Albert221** [comment]
It currently does not allow renaming, but this dash seems like a bug on our side. I'll fix it in a day or two

**Comment by RoyZengTW** [comment]
Thanks for the reply.
I have an addition issue is that the locale in arb content is `"@@locale": "en-hk" `.
It seems also change to "@@locale": "en_hk".

**Comment by RoyZengTW** [comment]
Thank you. You just save my day. 😄
