### ISSUE TITLE
about term prefix

### ISSUE THREAD

**Issue by RoyZengTW** [leancodepl/poe2arb#84]
I would like to know does the term prefix support multiple input like "A,B" ? 
Thanks.

**Comment by Albert221** [comment]
Hello,

We do not support having multiple term prefixes for a package and don't plan on introducing such a feature.

* Having multiple term prefixes introduces a problem of potential conflicts when there are `foo` and `prefix_foo` terms.
* Multiple term prefixes would also make it impossible to use the seed feature of `poe2arb`, as the tool would not know which term is supposed to have which prefix (and introducing that to metadata is something we're not planning to do).

The use case for term prefixes ideally is to separate translations of multiple packages within a project:

> ### Term prefix filtering
> 
> If you wish to use one POEditor project for multiple packages, ideally you do not want one package's terms to pollute all other packages. This is what term prefixes are for.
>
> &mdash;https://github.com/leancodepl/poe2arb#term-prefix-filtering

**Comment by RoyZengTW** [comment]
I got it. Thanks for reply. 😄
